// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Session struct {
	ID                     uuid.UUID
	CreatedAt              time.Time
	UpdatedAt              time.Time
	StartedAt              time.Time
	EndedAt                sql.NullTime
	PauseSeconds           int32
	UserID                 uuid.UUID
	PausedAt               sql.NullTime
	AssignToDayBeforeStart sql.NullBool
}

type User struct {
	ID                       uuid.UUID
	CreatedAt                time.Time
	UpdatedAt                time.Time
	Username                 string
	PasswordHash             []byte
	TimeZone                 string
	SessionIDHash            []byte
	SessionExpiresAt         sql.NullTime
	AwaitAssignDecisionUntil sql.NullTime
}
