// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type User struct {
	ID               uuid.UUID
	CreatedAt        time.Time
	UpdatedAt        time.Time
	Username         string
	PasswordHash     []byte
	TimeZone         string
	SessionIDHash    []byte
	SessionExpiresAt sql.NullTime
}
