// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.771
package main

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func register() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<html><head><title>Register</title><script src=\"https://unpkg.com/htmx.org@2.0.2\" integrity=\"sha384-Y7hw+L/jvKeWIRRkqWYfPcvVxHzVzn5REgzbawhxAuQGwX1XWe70vji+VSeHOThJ\" crossorigin=\"anonymous\"></script><link rel=\"stylesheet\" href=\"/css/register.css\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"></head><body onload=\"document.body.style.opacity=&#39;1&#39;;\"><div id=\"mainContainer\"><h1>Register</h1><form hx-target=\"#errMsgDiv\" hx-post=\"/users\"><input type=\"text\" id=\"username\" name=\"username\" placeholder=\"Username\"><br><input type=\"password\" id=\"password\" name=\"password\" placeholder=\"Password\"><br><input type=\"password\" id=\"confirmPassword\" name=\"confirmPassword\" placeholder=\"Confirm password\"><br><input type=\"submit\" value=\"Submit\"></form><p class=\"loginHint\">Already have an account? <a class=\"loginHint\" href=\"/login\">Login here</a></p><div id=\"errMsgDiv\"></div></div></body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}

var _ = templruntime.GeneratedTemplate
